/* global module */
module.exports = {
	"env": {"es2021": true, "node": true, "browser": true},
	"extends": "eslint:recommended",
	"ignorePatterns": ["!.eslintrc.js"],
	"parserOptions": {"sourceType": "module"},
	"rules": {
		"array-bracket-newline": [1, "consistent"],
		"array-bracket-spacing": [1, "never"],
		"array-element-newline": [2, "consistent"],
		"arrow-spacing": [2],
		"block-spacing": [0],
		"brace-style": [2, "stroustrup"],
		"camelcase": [1],
		"capitalized-comments": [0],
		"comma-dangle": [1],
		"comma-spacing": [1],
		"comma-style": [0],
		"computed-property-spacing": [1],
		"consistent-this": [0],
		"curly": [1, "multi-or-nest"],
		"eol-last": [2],
		"func-call-spacing": [2],
		"implicit-arrow-linebreak": [0],
		"indent": [2, "tab"],
		"key-spacing": [2],
		"line-comment-position": [0],
		"linebreak-style": [2],
		"lines-around-comment": [0],
		"max-depth": [1, 24],
		"max-len": [0, 144],
		"max-lines": [-0],
		"max-lines-per-function": [-0],
		"max-nested-callbacks": [1, 12],
		"max-params": [1, 24],
		"max-statements": [-0],
		"max-statements-per-line": [0],
		"multiline-comment-style": [0],
		"multiline-ternary": [0],
		"new-cap": [1],
		"new-parens": [0],
		"newline-per-chained-call": [0],
		"no-array-constructor": [1],
		"no-bitwise": [-0],
		"no-continue": [-0],
		"no-extra-parens": [2],
		"no-inline-comments": [-0],
		"no-lonely-if": [-0],
		"no-mixed-operators": [0],
		"no-mixed-spaces-and-tabs": [2],
		"no-multi-assign": [0],
		"no-multiple-empty-lines": [2, {"max": 3, "maxBOF": 0, "maxEOF": 0}],
		"no-negated-condition": [-0],
		"no-nested-ternary": [-0],
		"no-new-object": [1],
		"no-plusplus": [0],
		"no-tabs": [2, {"allowIndentationTabs": true}],
		"no-ternary": [-0],
		"no-trailing-spaces": [2],
		"no-underscore-dangle": [0],
		"no-unneeded-ternary": [1],
		"no-unused-vars": [1],
		"no-whitespace-before-property": [1],
		"nonblock-statement-body-position": [1, "below"],
		"object-curly-newline": [1, {"consistent": true}],
		"object-curly-spacing": [1, "never"],
		"object-property-newline": [2, {"allowAllPropertiesOnSameLine": true}],
		"one-var": [-0],
		"one-var-declaration-per-line": [0],
		"operator-assignment": [1],
		"operator-linebreak": [1],
		"padded-blocks": [2, "never"],
		"padding-line-between-statements": [0],
		"prefer-exponentiation-operator": [2],
		"prefer-object-spread": [1],
		"quote-props": [2, "always"],
		"quotes": [2],
		"semi": [2],
		"semi-spacing": [2],
		"sort-keys": [0],
		"sort-vars": [1],
		"space-before-blocks": [1],
		"space-before-function-paren": [2],
		"space-in-parens": [2],
		"space-infix-ops": [-0],
		"space-unary-ops": [1],
		"spaced-comment": [1, "always"],
		"switch-colon-spacing": [2],
		"template-tag-spacing": [1],
		"unicode-bom": [2, "never"],
		"wrap-regex": [-0]
	}
};
