#!/bin/sh
set -eu

for u2 in .user2.d/*; do
	"$u2" "$@" &
done

dest=/tmp/svscan$$
mkdir "$dest"
tar chC .s6 . | tar xC "$dest"
ln -s "$dest" ".svscan$$"
s6-rename ".svscan$$" .svscan

exec emptyenv -p s6-svscan -St0 "$dest"
