se ai noar bs=2 nocp dy=lastline enc=utf-8 hi=10000 hls is ls=2 sta wmnu

se sw=0 ts=4 lbr nu nuw=7 mouse=
se ls=2 stl=%F\ %y%r%h%w%m\ =%02B\ (%l,%v)[%L/%02p%%]
se swf dir=~/.vimstore bk bdir=~/.vimstore bkc=yes,breakhardlink
au BufWritePre * let &bex = strftime('@%F-%T~')

se t_kB=[Z

no U <C-r>

sy on
filet plugin indent on

au BufEnter *.ass set ft=ass
au BufEnter *.md set ft=markdown
au BufEnter fstab.* set ft=fstab

au BufEnter * if getline(1) =~ '^#!.*\<execlineb\>' | set ft=execlineb | en

au BufEnter nginx.conf set ft=nginx
au BufEnter /etc/hosts se ts=16

au FileType asm,fstab se ts=8 | no! <S-Tab> <Tab>
au FileType ass se nobomb nowrap
au FileType c,cpp se cin cino+=:0
au FileType crontab se bkc=yes
au FileType eruby let &ft = b:eruby_subtype | se syn=eruby
au FileType execlineb se cin cino=+0 syn=conf
au FileType html se ts=2

au BufEnter,FileType * let &sw = &ts

au BufWritePost ~/public_html/*.html silent! !gzip -kf <afile>

exe pathogen#infect('{local,bundle}/{}')

let g:html_indent_script1 = 'inc'
let g:html_indent_style1 = 'inc'
let g:SuperTabDefaultCompletionType = 'context'

ru macros/matchit.vim
