se ai noar bs=2 nocp dy=lastline enc=utf-8 hi=10000 hls is ls=2 sta wmnu

se sw=0 ts=4 lbr nu nuw=7 ls=2 bk bkc=yes,breakhardlink bdir=~/.vimstore dir=~/.vimstore
let &stl = '%F %y%r%h%w%m =%02B (%l,%v)[%L/%02p%%]'
au BufWritePre * let &bex = strftime('@%F-%T~')

no U <C-r>
se t_kB=[Z
" reclaim <S-Tab> from supertab
au VimEnter * no! <S-Tab> <Tab>

sy on
filet plugin indent on

au BufWritePost ~/public_html/*.html sil! !gzip -9kf <afile>

let g:SuperTabDefaultCompletionType = 'context'

ru macros/matchit.vim
