se ai ar bs=2 dy=lastline enc=utf-8 hi=10000 hls is ls=2 sta wmnu

se et sw=2 ts=2 lbr nu nuw=7 mouse=
se ls=2 stl=%F\ %y%r%h%w%m\ =%02B\ (%l,%v)[%L/%02p%%]
se swf dir=~/.vimstore bk bdir=~/.vimstore bkc=yes,breakhardlink
au BufWritePre * let &bex = strftime('@%F-%T~')

no U <C-r>

sy on
filet plugin indent on

au BufEnter *.ass setf ass
au BufEnter *.md setf markdown
au BufEnter */ng*.conf setf nginx

au BufEnter * if getline(1) =~ '^#!.*\<ash\>' | setf sh | en
au BufEnter * if getline(1) =~ '^#!.*\<execlineb\>' | setf execlineb | en

au BufEnter APKBUILD se ft=sh sw=8 ts=8 noet
au BufEnter /etc/hosts se ts=16 noet

au FileType asm se ts=8 sw=8 noet | no! <S-Tab> <Tab>
au FileType ass se nobomb nowrap
au FileType c,cpp se cin
au FileType crontab se bkc=yes
au FileType execlineb se cin cino=+0 syn=conf
au FileType asm se ts=8 sw=8 noet

exe pathogen#infect()

let g:html_indent_script1 = "inc"
let g:html_indent_style1 = "inc"
let g:SuperTabDefaultCompletionType = 'context'
